version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      # - echo testing...
      - echo building...
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-advanced
