version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing angualr...
      - npm install -g @angular/cli
  pre_build:
    commands:
      - echo installing npm packages ....
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building...
      - ng build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist/angular-advanced
