version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - nvm install 14
      - nvm use 14
  pre-build:
    commands:
      - echo installing npm packages ....
      - npm install
  build:
    commands:
      # - echo testing...
      - echo building...
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/angular-advanced
