AWSTemplateFormatVersion: 2010-09-09
Description: Static website hosting
Parameters:
  DomainName:
    Description: Domain name for the website
    Type: String
    Default: angular-advanced-dev.janithatennakoon.com
  HostedZone:
    Description: The full domain name e.g. www.janithatennakoon.com
    ConstraintDescription: must be a valid DNS zone name.
    Type: String
    Default: janithatennakoon.com
Mappings:
  RegionMap:
    us-east-1:
      S3hostedzoneID: Z3AQBSTGFYJSTF
      websiteendpoint: s3-website-us-east-1.amazonaws.com
    us-west-1:
      S3hostedzoneID: Z2F56UZL2M1ACD
      websiteendpoint: s3-website-us-west-1.amazonaws.com
    us-west-2:
      S3hostedzoneID: Z3BJ6K6RIION7M
      websiteendpoint: s3-website-us-west-2.amazonaws.com
    eu-west-1:
      S3hostedzoneID: Z1BKCTXD74EZPE
      websiteendpoint: s3-website-eu-west-1.amazonaws.com
    ap-southeast-1:
      S3hostedzoneID: Z3O0J2DXBE1FTB
      websiteendpoint: s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      S3hostedzoneID: Z1WCIGYICN2BYD
      websiteendpoint: s3-website-ap-southeast-2.amazonaws.com
    ap-northeast-1:
      S3hostedzoneID: Z2M4EHUR26P7ZW
      websiteendpoint: s3-website-ap-northeast-1.amazonaws.com
    sa-east-1:
      S3hostedzoneID: Z31GFT0UA1I2HV
      websiteendpoint: s3-website-sa-east-1.amazonaws.com
Resources:
  RootBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  ReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${RootBucket}/*
            Principal: '*'
  S3PublishUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub 'publish-to-${RootBucket}'
          PolicyDocument:
            Statement:
              - Action: 's3:*'
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:s3:::${RootBucket}'
                  - !Sub 'arn:aws:s3:::${RootBucket}/*'
  PublishCredentials:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref S3PublishUser
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      # HostedZoneName: !Sub
      #   - ${Domain}
      #   - Domain: !Ref DomainName
      HostedZoneName: !Sub '${HostedZone}.'
      Comment: Zone alias
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap [RegionMap, !Ref 'AWS::Region', S3hostedzoneID]
            DNSName: !FindInMap [RegionMap, !Ref 'AWS::Region', websiteendpoint]

Outputs:
  WebSiteUrl:
    Value: !GetAtt RootBucket.WebsiteURL
    Description: URL for the website hosted on S3
